/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.swagger.petstore3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.petstore3.DateTimeHelper;
import java.time.LocalDateTime;

/**
 * This is a model class for Order type.
 */
public class Order {
    private Long id;
    private Long petId;
    private Integer quantity;
    private LocalDateTime shipDate;
    private OrderStatusEnum orderStatus;
    private Boolean complete;

    /**
     * Default constructor.
     */
    public Order() {
        orderStatus = OrderStatusEnum.APPROVED;
    }

    /**
     * Initialization constructor.
     * @param  id  Long value for id.
     * @param  petId  Long value for petId.
     * @param  quantity  Integer value for quantity.
     * @param  shipDate  LocalDateTime value for shipDate.
     * @param  orderStatus  OrderStatusEnum value for orderStatus.
     * @param  complete  Boolean value for complete.
     */
    public Order(
            Long id,
            Long petId,
            Integer quantity,
            LocalDateTime shipDate,
            OrderStatusEnum orderStatus,
            Boolean complete) {
        this.id = id;
        this.petId = petId;
        this.quantity = quantity;
        this.shipDate = shipDate;
        this.orderStatus = orderStatus;
        this.complete = complete;
    }

    /**
     * Getter for Id.
     * @return Returns the Long
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Long getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for Long
     */
    @JsonSetter("id")
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for PetId.
     * @return Returns the Long
     */
    @JsonGetter("petId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Long getPetId() {
        return petId;
    }

    /**
     * Setter for PetId.
     * @param petId Value for Long
     */
    @JsonSetter("petId")
    public void setPetId(Long petId) {
        this.petId = petId;
    }

    /**
     * Getter for Quantity.
     * @return Returns the Integer
     */
    @JsonGetter("quantity")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * Setter for Quantity.
     * @param quantity Value for Integer
     */
    @JsonSetter("quantity")
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * Getter for ShipDate.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("shipDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getShipDate() {
        return shipDate;
    }

    /**
     * Setter for ShipDate.
     * @param shipDate Value for LocalDateTime
     */
    @JsonSetter("shipDate")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setShipDate(LocalDateTime shipDate) {
        this.shipDate = shipDate;
    }

    /**
     * Getter for OrderStatus.
     * Order Status
     * @return Returns the OrderStatusEnum
     */
    @JsonGetter("orderStatus")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public OrderStatusEnum getOrderStatus() {
        return orderStatus;
    }

    /**
     * Setter for OrderStatus.
     * Order Status
     * @param orderStatus Value for OrderStatusEnum
     */
    @JsonSetter("orderStatus")
    public void setOrderStatus(OrderStatusEnum orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * Getter for Complete.
     * @return Returns the Boolean
     */
    @JsonGetter("complete")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getComplete() {
        return complete;
    }

    /**
     * Setter for Complete.
     * @param complete Value for Boolean
     */
    @JsonSetter("complete")
    public void setComplete(Boolean complete) {
        this.complete = complete;
    }

    /**
     * Converts this Order into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Order [" + "id=" + id + ", petId=" + petId + ", quantity=" + quantity
                + ", shipDate=" + shipDate + ", orderStatus=" + orderStatus + ", complete="
                + complete + "]";
    }

    /**
     * Builds a new {@link Order.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Order.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .petId(getPetId())
                .quantity(getQuantity())
                .shipDate(getShipDate())
                .orderStatus(getOrderStatus())
                .complete(getComplete());
        return builder;
    }

    /**
     * Class to build instances of {@link Order}.
     */
    public static class Builder {
        private Long id;
        private Long petId;
        private Integer quantity;
        private LocalDateTime shipDate;
        private OrderStatusEnum orderStatus = OrderStatusEnum.APPROVED;
        private Boolean complete;



        /**
         * Setter for id.
         * @param  id  Long value for id.
         * @return Builder
         */
        public Builder id(Long id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for petId.
         * @param  petId  Long value for petId.
         * @return Builder
         */
        public Builder petId(Long petId) {
            this.petId = petId;
            return this;
        }

        /**
         * Setter for quantity.
         * @param  quantity  Integer value for quantity.
         * @return Builder
         */
        public Builder quantity(Integer quantity) {
            this.quantity = quantity;
            return this;
        }

        /**
         * Setter for shipDate.
         * @param  shipDate  LocalDateTime value for shipDate.
         * @return Builder
         */
        public Builder shipDate(LocalDateTime shipDate) {
            this.shipDate = shipDate;
            return this;
        }

        /**
         * Setter for orderStatus.
         * @param  orderStatus  OrderStatusEnum value for orderStatus.
         * @return Builder
         */
        public Builder orderStatus(OrderStatusEnum orderStatus) {
            this.orderStatus = orderStatus;
            return this;
        }

        /**
         * Setter for complete.
         * @param  complete  Boolean value for complete.
         * @return Builder
         */
        public Builder complete(Boolean complete) {
            this.complete = complete;
            return this;
        }

        /**
         * Builds a new {@link Order} object using the set fields.
         * @return {@link Order}
         */
        public Order build() {
            return new Order(id, petId, quantity, shipDate, orderStatus, complete);
        }
    }
}
