/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.swagger.petstore3.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * PetStatusEnum to be used.
 */
public enum PetStatusEnum {
    AVAILABLE,

    PENDING,

    SOLD;


    private static TreeMap<String, PetStatusEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        AVAILABLE.value = "available";
        PENDING.value = "pending";
        SOLD.value = "sold";

        valueMap.put("available", AVAILABLE);
        valueMap.put("pending", PENDING);
        valueMap.put("sold", SOLD);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static PetStatusEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PetStatusEnum values to list of string values.
     * @param toConvert The list of PetStatusEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<PetStatusEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (PetStatusEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 