/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.swagger.petstore3.controllers;

import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.MutliPartRequestType;
import io.swagger.petstore3.ApiHelper;
import io.swagger.petstore3.Server;
import io.swagger.petstore3.exceptions.ApiException;
import io.swagger.petstore3.http.request.HttpMethod;
import io.swagger.petstore3.models.Category;
import io.swagger.petstore3.models.Pet;
import io.swagger.petstore3.models.PetImage;
import io.swagger.petstore3.models.PetStatusEnum;
import io.swagger.petstore3.models.StatusEnum;
import io.swagger.petstore3.models.Tag;
import io.swagger.petstore3.utilities.FileWrapper;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class PetController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public PetController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Update an existing pet by Id.
     * @param  name  Required parameter: Example:
     * @param  photoUrls  Required parameter: Example:
     * @param  id  Optional parameter: Example:
     * @param  category  Optional parameter: Example:
     * @param  tags  Optional parameter: Example:
     * @param  petStatus  Optional parameter: pet status in the store
     * @return    Returns the Pet response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public Pet updatePet(
            final String name,
            final List<String> photoUrls,
            final Long id,
            final Category category,
            final List<Tag> tags,
            final PetStatusEnum petStatus) throws ApiException, IOException {
        return prepareUpdatePetRequest(name, photoUrls, id, category, tags, petStatus).execute();
    }

    /**
     * Update an existing pet by Id.
     * @param  name  Required parameter: Example:
     * @param  photoUrls  Required parameter: Example:
     * @param  id  Optional parameter: Example:
     * @param  category  Optional parameter: Example:
     * @param  tags  Optional parameter: Example:
     * @param  petStatus  Optional parameter: pet status in the store
     * @return    Returns the Pet response from the API call
     */
    public CompletableFuture<Pet> updatePetAsync(
            final String name,
            final List<String> photoUrls,
            final Long id,
            final Category category,
            final List<Tag> tags,
            final PetStatusEnum petStatus) {
        try { 
            return prepareUpdatePetRequest(name, photoUrls, id, category, tags, petStatus).executeAsync(); 
        } catch (Exception e) {  
            throw new CompletionException(e); 
        }
    }

    /**
     * Builds the ApiCall object for updatePet.
     */
    private ApiCall<Pet, ApiException> prepareUpdatePetRequest(
            final String name,
            final List<String> photoUrls,
            final Long id,
            final Category category,
            final List<Tag> tags,
            final PetStatusEnum petStatus) throws IOException {
        return new ApiCall.Builder<Pet, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/pet")
                        .formParam(param -> param.key("name")
                                .value(name))
                        .formParam(param -> param.key("photoUrls")
                                .value(photoUrls))
                        .formParam(param -> param.key("id")
                                .value(id).isRequired(false))
                        .formParam(param -> param.key("category")
                                .value(category).isRequired(false))
                        .formParam(param -> param.key("tags")
                                .value(tags).isRequired(false))
                        .formParam(param -> param.key("petStatus")
                                .value((petStatus != null) ? petStatus.value() : null).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/x-www-form-urlencoded").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .authenticationKey(BaseController.AUTHENTICATION_KEY)
                        .httpMethod(HttpMethod.PUT))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, Pet.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Invalid ID supplied",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("Pet not found",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("405",
                                 ErrorCase.setReason("Validation exception",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Add a new pet to the store.
     * @param  name  Required parameter: Example:
     * @param  photoUrls  Required parameter: Example:
     * @param  id  Optional parameter: Example:
     * @param  category  Optional parameter: Example:
     * @param  tags  Optional parameter: Example:
     * @param  petStatus  Optional parameter: pet status in the store
     * @return    Returns the Pet response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public Pet addPet(
            final String name,
            final List<String> photoUrls,
            final Long id,
            final Category category,
            final List<Tag> tags,
            final PetStatusEnum petStatus) throws ApiException, IOException {
        return prepareAddPetRequest(name, photoUrls, id, category, tags, petStatus).execute();
    }

    /**
     * Add a new pet to the store.
     * @param  name  Required parameter: Example:
     * @param  photoUrls  Required parameter: Example:
     * @param  id  Optional parameter: Example:
     * @param  category  Optional parameter: Example:
     * @param  tags  Optional parameter: Example:
     * @param  petStatus  Optional parameter: pet status in the store
     * @return    Returns the Pet response from the API call
     */
    public CompletableFuture<Pet> addPetAsync(
            final String name,
            final List<String> photoUrls,
            final Long id,
            final Category category,
            final List<Tag> tags,
            final PetStatusEnum petStatus) {
        try { 
            return prepareAddPetRequest(name, photoUrls, id, category, tags, petStatus).executeAsync(); 
        } catch (Exception e) {  
            throw new CompletionException(e); 
        }
    }

    /**
     * Builds the ApiCall object for addPet.
     */
    private ApiCall<Pet, ApiException> prepareAddPetRequest(
            final String name,
            final List<String> photoUrls,
            final Long id,
            final Category category,
            final List<Tag> tags,
            final PetStatusEnum petStatus) throws IOException {
        return new ApiCall.Builder<Pet, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/pet")
                        .formParam(param -> param.key("name")
                                .value(name))
                        .formParam(param -> param.key("photoUrls")
                                .value(photoUrls))
                        .formParam(param -> param.key("id")
                                .value(id).isRequired(false))
                        .formParam(param -> param.key("category")
                                .value(category).isRequired(false))
                        .formParam(param -> param.key("tags")
                                .value(tags).isRequired(false))
                        .formParam(param -> param.key("petStatus")
                                .value((petStatus != null) ? petStatus.value() : null).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/x-www-form-urlencoded").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .authenticationKey(BaseController.AUTHENTICATION_KEY)
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, Pet.class))
                        .nullify404(false)
                        .localErrorCase("405",
                                 ErrorCase.setReason("Invalid input",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Multiple status values can be provided with comma separated strings.
     * @param  status  Optional parameter: Status values that need to be considered for filter
     * @return    Returns the List of Pet response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public List<Pet> findPetsByStatus(
            final StatusEnum status) throws ApiException, IOException {
        return prepareFindPetsByStatusRequest(status).execute();
    }

    /**
     * Multiple status values can be provided with comma separated strings.
     * @param  status  Optional parameter: Status values that need to be considered for filter
     * @return    Returns the List of Pet response from the API call
     */
    public CompletableFuture<List<Pet>> findPetsByStatusAsync(
            final StatusEnum status) {
        try { 
            return prepareFindPetsByStatusRequest(status).executeAsync(); 
        } catch (Exception e) {  
            throw new CompletionException(e); 
        }
    }

    /**
     * Builds the ApiCall object for findPetsByStatus.
     */
    private ApiCall<List<Pet>, ApiException> prepareFindPetsByStatusRequest(
            final StatusEnum status) throws IOException {
        return new ApiCall.Builder<List<Pet>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/pet/findByStatus")
                        .queryParam(param -> param.key("status")
                                .value((status != null) ? status.value() : "available").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .authenticationKey(BaseController.AUTHENTICATION_KEY)
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserializeArray(response,
                                        Pet[].class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Invalid status value",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
     * @param  tags  Optional parameter: Tags to filter by
     * @return    Returns the List of Pet response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public List<Pet> findPetsByTags(
            final List<String> tags) throws ApiException, IOException {
        return prepareFindPetsByTagsRequest(tags).execute();
    }

    /**
     * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
     * @param  tags  Optional parameter: Tags to filter by
     * @return    Returns the List of Pet response from the API call
     */
    public CompletableFuture<List<Pet>> findPetsByTagsAsync(
            final List<String> tags) {
        try { 
            return prepareFindPetsByTagsRequest(tags).executeAsync(); 
        } catch (Exception e) {  
            throw new CompletionException(e); 
        }
    }

    /**
     * Builds the ApiCall object for findPetsByTags.
     */
    private ApiCall<List<Pet>, ApiException> prepareFindPetsByTagsRequest(
            final List<String> tags) throws IOException {
        return new ApiCall.Builder<List<Pet>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/pet/findByTags")
                        .queryParam(param -> param.key("tags")
                                .value(tags).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .authenticationKey(BaseController.AUTHENTICATION_KEY)
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserializeArray(response,
                                        Pet[].class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Invalid tag value",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Returns a single pet.
     * @param  petId  Required parameter: ID of pet to return
     * @return    Returns the Pet response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public Pet getPetById(
            final long petId) throws ApiException, IOException {
        return prepareGetPetByIdRequest(petId).execute();
    }

    /**
     * Returns a single pet.
     * @param  petId  Required parameter: ID of pet to return
     * @return    Returns the Pet response from the API call
     */
    public CompletableFuture<Pet> getPetByIdAsync(
            final long petId) {
        try { 
            return prepareGetPetByIdRequest(petId).executeAsync(); 
        } catch (Exception e) {  
            throw new CompletionException(e); 
        }
    }

    /**
     * Builds the ApiCall object for getPetById.
     */
    private ApiCall<Pet, ApiException> prepareGetPetByIdRequest(
            final long petId) throws IOException {
        return new ApiCall.Builder<Pet, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/pet/{petId}")
                        .templateParam(param -> param.key("petId").value(petId).isRequired(false)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .authenticationKey(BaseController.AUTHENTICATION_KEY)
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, Pet.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Invalid ID supplied",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("Pet not found",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Updates a pet in the store with form data.
     * @param  petId  Required parameter: ID of pet that needs to be updated
     * @param  name  Optional parameter: Name of pet that needs to be updated
     * @param  status  Optional parameter: Status of pet that needs to be updated
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public void updatePetWithForm(
            final long petId,
            final String name,
            final String status) throws ApiException, IOException {
        prepareUpdatePetWithFormRequest(petId, name, status).execute();
    }

    /**
     * Updates a pet in the store with form data.
     * @param  petId  Required parameter: ID of pet that needs to be updated
     * @param  name  Optional parameter: Name of pet that needs to be updated
     * @param  status  Optional parameter: Status of pet that needs to be updated
     * @return    Returns the void response from the API call
     */
    public CompletableFuture<Void> updatePetWithFormAsync(
            final long petId,
            final String name,
            final String status) {
        try { 
            return prepareUpdatePetWithFormRequest(petId, name, status).executeAsync(); 
        } catch (Exception e) {  
            throw new CompletionException(e); 
        }
    }

    /**
     * Builds the ApiCall object for updatePetWithForm.
     */
    private ApiCall<Void, ApiException> prepareUpdatePetWithFormRequest(
            final long petId,
            final String name,
            final String status) throws IOException {
        return new ApiCall.Builder<Void, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/pet/{petId}")
                        .queryParam(param -> param.key("name")
                                .value(name).isRequired(false))
                        .queryParam(param -> param.key("status")
                                .value(status).isRequired(false))
                        .templateParam(param -> param.key("petId").value(petId).isRequired(false)
                                .shouldEncode(true))
                        .authenticationKey(BaseController.AUTHENTICATION_KEY)
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .nullify404(false)
                        .localErrorCase("405",
                                 ErrorCase.setReason("Invalid input",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * delete a pet.
     * @param  petId  Required parameter: Pet id to delete
     * @param  apiKey  Optional parameter: Example:
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public void deletePet(
            final long petId,
            final String apiKey) throws ApiException, IOException {
        prepareDeletePetRequest(petId, apiKey).execute();
    }

    /**
     * delete a pet.
     * @param  petId  Required parameter: Pet id to delete
     * @param  apiKey  Optional parameter: Example:
     * @return    Returns the void response from the API call
     */
    public CompletableFuture<Void> deletePetAsync(
            final long petId,
            final String apiKey) {
        try { 
            return prepareDeletePetRequest(petId, apiKey).executeAsync(); 
        } catch (Exception e) {  
            throw new CompletionException(e); 
        }
    }

    /**
     * Builds the ApiCall object for deletePet.
     */
    private ApiCall<Void, ApiException> prepareDeletePetRequest(
            final long petId,
            final String apiKey) throws IOException {
        return new ApiCall.Builder<Void, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/pet/{petId}")
                        .templateParam(param -> param.key("petId").value(petId).isRequired(false)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("api_key")
                                .value(apiKey).isRequired(false))
                        .authenticationKey(BaseController.AUTHENTICATION_KEY)
                        .httpMethod(HttpMethod.DELETE))
                .responseHandler(responseHandler -> responseHandler
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Invalid pet value",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * uploads an image.
     * @param  petId  Required parameter: ID of pet to update
     * @param  additionalMetadata  Optional parameter: Additional Metadata
     * @param  body  Optional parameter: Example:
     * @return    Returns the PetImage response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public PetImage uploadFile(
            final long petId,
            final String additionalMetadata,
            final FileWrapper body) throws ApiException, IOException {
        return prepareUploadFileRequest(petId, additionalMetadata, body).execute();
    }

    /**
     * uploads an image.
     * @param  petId  Required parameter: ID of pet to update
     * @param  additionalMetadata  Optional parameter: Additional Metadata
     * @param  body  Optional parameter: Example:
     * @return    Returns the PetImage response from the API call
     */
    public CompletableFuture<PetImage> uploadFileAsync(
            final long petId,
            final String additionalMetadata,
            final FileWrapper body) {
        try { 
            return prepareUploadFileRequest(petId, additionalMetadata, body).executeAsync(); 
        } catch (Exception e) {  
            throw new CompletionException(e); 
        }
    }

    /**
     * Builds the ApiCall object for uploadFile.
     */
    private ApiCall<PetImage, ApiException> prepareUploadFileRequest(
            final long petId,
            final String additionalMetadata,
            final FileWrapper body) throws IOException {
        return new ApiCall.Builder<PetImage, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/pet/{petId}/uploadImage")
                        .formParam(param -> param.key("body")
                                .value(body)
                                .multiPartRequestType(MutliPartRequestType.MULTI_PART_FILE)
                                .multipartHeaders("content-type", "application/octect-stream"))
                        .queryParam(param -> param.key("additionalMetadata")
                                .value(additionalMetadata).isRequired(false))
                        .templateParam(param -> param.key("petId").value(petId).isRequired(false)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/octet-stream").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .authenticationKey(BaseController.AUTHENTICATION_KEY)
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, PetImage.class))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}